import '../models/exercise_library_item.dart';
import 'exercise_categories.dart';

const exerciseDatabase = [
  ExerciseLibraryItem(
    id: 'press_pecho_maquina',
    name: 'Press pecho máquina',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.triceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.horizontalPush,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_banca_barra',
      'press_hombro_maquina',
    ],
    techniqueSteps: [
      'Ajusta el asiento para que las empuñaduras queden a la altura media del pecho.',
      'Apoya la espalda, junta ligeramente las escápulas y empuja sin bloquear los codos con fuerza.',
      'Vuelve de forma controlada hasta sentir estiramiento cómodo en el pecho.',
    ],
    commonMistakes: [
      'Separar la espalda del respaldo.',
      'Subir los hombros hacia las orejas.',
      'Rebotar al final del recorrido.',
    ],
    safetyNote:
        'Usa un rango sin dolor y reduce carga si pierdes control en hombros o muñecas.',
    imageAsset: 'assets/exercises/press_pecho_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'press_banca_barra',
    name: 'Press banca con barra',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.triceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.horizontalPush,
    equipment: ExerciseEquipment.barbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_pecho_maquina',
      'press_hombro_maquina',
    ],
    techniqueSteps: [
      'Coloca los pies firmes, escápulas estables y agarre simétrico.',
      'Baja la barra hacia la zona media-baja del pecho con antebrazos casi verticales.',
      'Empuja manteniendo tensión corporal y una trayectoria controlada.',
    ],
    commonMistakes: [
      'Abrir demasiado los codos.',
      'Rebotar la barra en el pecho.',
      'Perder estabilidad de pies o escápulas.',
    ],
    safetyNote:
        'Entrena con topes o ayuda externa si usas cargas exigentes; no fuerces repeticiones dudosas.',
    imageAsset: 'assets/exercises/press_banca_con_barra.png',
  ),
  ExerciseLibraryItem(
    id: 'jalon_al_pecho',
    name: 'Jalón al pecho',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.biceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.verticalPull,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'remo_sentado_polea',
      'curl_biceps_mancuernas',
    ],
    techniqueSteps: [
      'Fija los muslos bajo el soporte y toma la barra con agarre estable.',
      'Lleva los codos hacia abajo y atrás hasta acercar la barra al pecho.',
      'Regresa controlando la subida sin perder la postura del torso.',
    ],
    commonMistakes: [
      'Tirar con impulso del tronco.',
      'Llevar la barra detrás de la nuca.',
      'Encoger los hombros durante el tirón.',
    ],
    safetyNote:
        'Evita tirones bruscos y mantén el cuello relajado durante todo el recorrido.',
    imageAsset: 'assets/exercises/jalon_al_pecho.png',
  ),
  ExerciseLibraryItem(
    id: 'remo_sentado_polea',
    name: 'Remo sentado en polea',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.biceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.horizontalPull,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'jalon_al_pecho',
      'curl_biceps_mancuernas',
    ],
    techniqueSteps: [
      'Siéntate erguido con pies apoyados y brazos extendidos sin redondear la espalda.',
      'Tira llevando los codos atrás y acerca el agarre al abdomen.',
      'Vuelve lento dejando que las escápulas se muevan sin perder control lumbar.',
    ],
    commonMistakes: [
      'Balancear el torso para mover más peso.',
      'Redondear la zona lumbar.',
      'Terminar el tirón con las muñecas dobladas.',
    ],
    safetyNote:
        'Reduce carga si necesitas impulsarte con el tronco o notas tensión lumbar incómoda.',
    imageAsset: 'assets/exercises/remo_sentado_polea.png',
  ),
  ExerciseLibraryItem(
    id: 'prensa_piernas',
    name: 'Prensa de piernas',
    primaryMuscle: ExerciseMuscles.quadriceps,
    secondaryMuscles: [
      ExerciseMuscles.glutes,
      ExerciseMuscles.hamstrings,
    ],
    movementPattern: MovementPatterns.squat,
    equipment: ExerciseEquipment.legPress,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'sentadilla_goblet',
      'peso_muerto_rumano',
    ],
    techniqueSteps: [
      'Coloca los pies a una anchura cómoda y apoya toda la espalda en el respaldo.',
      'Desbloquea la prensa y baja controlando hasta una profundidad estable.',
      'Empuja con todo el pie sin bloquear agresivamente las rodillas.',
    ],
    commonMistakes: [
      'Despegar la pelvis del asiento.',
      'Juntar las rodillas hacia dentro.',
      'Bajar más allá del rango que puedes controlar.',
    ],
    safetyNote:
        'Usa los seguros de la máquina y evita rangos que provoquen dolor en rodilla, cadera o espalda.',
    imageAsset: 'assets/exercises/prensa_piernas.png',
  ),
  ExerciseLibraryItem(
    id: 'sentadilla_goblet',
    name: 'Sentadilla goblet',
    primaryMuscle: ExerciseMuscles.quadriceps,
    secondaryMuscles: [
      ExerciseMuscles.glutes,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.squat,
    equipment: ExerciseEquipment.kettlebell,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'prensa_piernas',
      'peso_muerto_rumano',
    ],
    techniqueSteps: [
      'Sostén la carga cerca del pecho y coloca los pies en una base estable.',
      'Baja entre las piernas manteniendo el torso firme y las rodillas alineadas.',
      'Sube empujando el suelo y manteniendo la carga pegada al cuerpo.',
    ],
    commonMistakes: [
      'Dejar que los talones se levanten.',
      'Perder tensión abdominal.',
      'Colapsar las rodillas hacia dentro.',
    ],
    safetyNote:
        'Elige una carga que puedas sostener cerca del pecho sin compensar con la espalda.',
    imageAsset: 'assets/exercises/sentadilla_goblet.png',
  ),
  ExerciseLibraryItem(
    id: 'peso_muerto_rumano',
    name: 'Peso muerto rumano',
    primaryMuscle: ExerciseMuscles.hamstrings,
    secondaryMuscles: [
      ExerciseMuscles.glutes,
      ExerciseMuscles.back,
    ],
    movementPattern: MovementPatterns.hinge,
    equipment: ExerciseEquipment.barbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'sentadilla_goblet',
      'prensa_piernas',
    ],
    techniqueSteps: [
      'Sujeta la barra cerca del cuerpo con rodillas ligeramente flexionadas.',
      'Lleva la cadera atrás manteniendo la espalda neutra y la barra pegada a las piernas.',
      'Sube extendiendo la cadera cuando notes tensión clara en isquiosurales.',
    ],
    commonMistakes: [
      'Convertirlo en una sentadilla.',
      'Alejar la barra del cuerpo.',
      'Redondear la espalda para buscar más profundidad.',
    ],
    safetyNote:
        'Prioriza el control de la espalda y detén el recorrido antes de perder posición neutra.',
    imageAsset: 'assets/exercises/peso_muerto_rumano.png',
  ),
  ExerciseLibraryItem(
    id: 'press_hombro_maquina',
    name: 'Press hombro máquina',
    primaryMuscle: ExerciseMuscles.shoulders,
    secondaryMuscles: [
      ExerciseMuscles.triceps,
      ExerciseMuscles.chest,
    ],
    movementPattern: MovementPatterns.verticalPush,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_pecho_maquina',
      'press_banca_barra',
    ],
    techniqueSteps: [
      'Ajusta el asiento para empezar con agarres cerca de la altura de los hombros.',
      'Empuja hacia arriba sin arquear la espalda ni encoger el cuello.',
      'Baja con control hasta una posición cómoda para el hombro.',
    ],
    commonMistakes: [
      'Arquear la zona lumbar.',
      'Bloquear los codos de forma brusca.',
      'Bajar más allá de un rango cómodo.',
    ],
    safetyNote:
        'Si aparece molestia anterior de hombro, reduce rango o cambia a una alternativa más cómoda.',
    imageAsset: 'assets/exercises/press_hombro_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_biceps_mancuernas',
    name: 'Curl bíceps con mancuernas',
    primaryMuscle: ExerciseMuscles.biceps,
    secondaryMuscles: [
      ExerciseMuscles.forearms,
    ],
    movementPattern: MovementPatterns.elbowFlexion,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'jalon_al_pecho',
      'remo_sentado_polea',
    ],
    techniqueSteps: [
      'Mantén los codos cerca del cuerpo y las muñecas neutras.',
      'Flexiona los codos sin balancear el tronco.',
      'Baja las mancuernas de forma lenta hasta extender casi por completo.',
    ],
    commonMistakes: [
      'Usar impulso de cadera o espalda.',
      'Mover los codos hacia delante en exceso.',
      'Doblar las muñecas al subir.',
    ],
    safetyNote:
        'Elige una carga que permita controlar la bajada y no irrite codos o muñecas.',
    imageAsset: 'assets/exercises/curl_biceps_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'triceps_polea_cuerda',
    name: 'Tríceps polea con cuerda',
    primaryMuscle: ExerciseMuscles.triceps,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.elbowExtension,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_pecho_maquina',
      'press_hombro_maquina',
    ],
    techniqueSteps: [
      'Colócate estable frente a la polea con los codos pegados al costado.',
      'Extiende los codos separando ligeramente la cuerda al final.',
      'Regresa controlando la subida sin dejar que los codos se adelanten.',
    ],
    commonMistakes: [
      'Inclinar todo el cuerpo para empujar.',
      'Mover los hombros en lugar de extender los codos.',
      'Soltar la cuerda sin controlar la fase de vuelta.',
    ],
    safetyNote:
        'Evita bloquear con violencia y ajusta la carga si notas molestias en codos.',
    imageAsset: 'assets/exercises/triceps_polea_cuerda.png',
  ),
  ExerciseLibraryItem(
    id: 'press_inclinado_mancuernas',
    name: 'Press inclinado con mancuernas',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
      ExerciseMuscles.triceps,
    ],
    movementPattern: MovementPatterns.horizontalPush,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_banca_barra',
      'press_pecho_maquina',
      'aperturas_maquina',
    ],
    techniqueSteps: [
      'Ajusta el banco con una inclinación moderada y apoya bien la espalda.',
      'Baja las mancuernas con control hasta una posición cómoda para el hombro.',
      'Empuja hacia arriba manteniendo muñecas estables y codos bajo control.',
    ],
    commonMistakes: [
      'Usar una inclinación excesiva y cargar demasiado el hombro.',
      'Chocar las mancuernas arriba.',
      'Arquear la espalda para completar repeticiones.',
    ],
    safetyNote:
        'No fuerces profundidad si molesta el hombro; baja carga o elige una alternativa estable.',
    imageAsset: 'assets/exercises/press_inclinado_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'aperturas_maquina',
    name: 'Aperturas en máquina',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.chestIsolation,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'aperturas_mancuernas',
      'press_pecho_maquina',
      'press_inclinado_mancuernas',
    ],
    techniqueSteps: [
      'Ajusta el asiento para que los agarres queden alineados con el pecho.',
      'Cierra los brazos con codos ligeramente flexionados y pecho estable.',
      'Vuelve lento hasta notar estiramiento cómodo.',
    ],
    commonMistakes: [
      'Llevar los hombros hacia delante al cerrar.',
      'Usar impulso en la primera parte.',
      'Abrir más de lo que permite el hombro.',
    ],
    safetyNote:
        'Mantén un recorrido cómodo y cambia el rango si aparece molestia anterior de hombro.',
    imageAsset: 'assets/exercises/aperturas_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'aperturas_mancuernas',
    name: 'Aperturas con mancuernas',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.chestIsolation,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'aperturas_maquina',
      'press_inclinado_mancuernas',
      'press_pecho_maquina',
    ],
    techniqueSteps: [
      'Túmbate con las mancuernas sobre el pecho y codos suaves.',
      'Abre los brazos en arco controlado sin perder estabilidad escapular.',
      'Cierra llevando las mancuernas sobre el pecho sin golpearlas.',
    ],
    commonMistakes: [
      'Convertir el movimiento en un press.',
      'Bajar demasiado buscando más recorrido.',
      'Perder control de las muñecas.',
    ],
    safetyNote:
        'Usa cargas moderadas y evita rangos profundos si no puedes controlarlos.',
    imageAsset: 'assets/exercises/aperturas_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'fondos_asistidos',
    name: 'Fondos asistidos',
    primaryMuscle: ExerciseMuscles.chest,
    secondaryMuscles: [
      ExerciseMuscles.triceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.horizontalPush,
    equipment: ExerciseEquipment.assistedMachine,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_pecho_maquina',
      'press_banca_barra',
      'fondos_banco',
    ],
    techniqueSteps: [
      'Ajusta la asistencia para moverte sin perder control.',
      'Inclina ligeramente el torso y baja con codos estables.',
      'Empuja hasta extender los brazos sin bloquear con brusquedad.',
    ],
    commonMistakes: [
      'Bajar demasiado rápido.',
      'Encoger hombros en la parte baja.',
      'Usar poca asistencia antes de dominar la técnica.',
    ],
    safetyNote:
        'No fuerces profundidad si el hombro no se siente estable; aumenta asistencia o cambia de ejercicio.',
    imageAsset: 'assets/exercises/fondos_asistidos.png',
  ),
  ExerciseLibraryItem(
    id: 'jalon_agarre_neutro',
    name: 'Jalón agarre neutro',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.biceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.verticalPull,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'jalon_al_pecho',
      'remo_sentado_polea',
      'remo_maquina',
    ],
    techniqueSteps: [
      'Agarra el accesorio neutro y fija los muslos bajo el soporte.',
      'Tira llevando los codos hacia abajo y cerca del torso.',
      'Controla la subida hasta extender los brazos sin perder postura.',
    ],
    commonMistakes: [
      'Tirar con balanceo del tronco.',
      'Cerrar demasiado el cuello.',
      'Soltar la fase excéntrica.',
    ],
    safetyNote:
        'Mantén un ritmo controlado y reduce carga si necesitas impulsarte.',
    imageAsset: 'assets/exercises/jalon_agarre_neutro.png',
  ),
  ExerciseLibraryItem(
    id: 'remo_mancuerna',
    name: 'Remo con mancuerna',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.biceps,
      ExerciseMuscles.shoulders,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.horizontalPull,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'remo_sentado_polea',
      'remo_maquina',
      'jalon_agarre_neutro',
    ],
    techniqueSteps: [
      'Apoya una mano en banco o soporte y deja la espalda estable.',
      'Tira de la mancuerna hacia la cadera con el codo cerca del cuerpo.',
      'Baja controlando sin girar el tronco.',
    ],
    commonMistakes: [
      'Rotar el torso para subir más peso.',
      'Encoger el hombro al final del tirón.',
      'Alejar demasiado el codo del cuerpo.',
    ],
    safetyNote:
        'Si pierdes estabilidad lumbar, baja la carga o usa una variante con apoyo.',
    imageAsset: 'assets/exercises/remo_con_mancuerna.png',
  ),
  ExerciseLibraryItem(
    id: 'remo_maquina',
    name: 'Remo en máquina',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.biceps,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.horizontalPull,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'remo_sentado_polea',
      'remo_mancuerna',
      'jalon_al_pecho',
    ],
    techniqueSteps: [
      'Ajusta asiento y pecho para que el tirón salga cómodo.',
      'Lleva los codos atrás sin despegarte del apoyo.',
      'Vuelve lento permitiendo que la espalda se estire sin redondearte.',
    ],
    commonMistakes: [
      'Separar el pecho del apoyo.',
      'Tirar solo con brazos.',
      'Subir hombros hacia las orejas.',
    ],
    safetyNote:
        'Ajusta el recorrido y la carga para evitar tirones en cuello o zona lumbar.',
    imageAsset: 'assets/exercises/remo_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'pullover_polea',
    name: 'Pullover en polea',
    primaryMuscle: ExerciseMuscles.back,
    secondaryMuscles: [
      ExerciseMuscles.chest,
      ExerciseMuscles.triceps,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.verticalPull,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'jalon_al_pecho',
      'jalon_agarre_neutro',
      'remo_sentado_polea',
    ],
    techniqueSteps: [
      'Colócate frente a la polea alta con brazos casi extendidos.',
      'Lleva el agarre hacia los muslos manteniendo el torso firme.',
      'Sube controlando hasta notar estiramiento en la espalda.',
    ],
    commonMistakes: [
      'Flexionar y extender los codos como un tríceps.',
      'Arquear la espalda para terminar el recorrido.',
      'Usar demasiado impulso.',
    ],
    safetyNote:
        'Trabaja con carga moderada y evita compensar con la zona lumbar.',
    imageAsset: 'assets/exercises/pullover_polea.png',
  ),
  ExerciseLibraryItem(
    id: 'sentadilla_multipower',
    name: 'Sentadilla en multipower',
    primaryMuscle: ExerciseMuscles.quadriceps,
    secondaryMuscles: [
      ExerciseMuscles.glutes,
      ExerciseMuscles.hamstrings,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.squat,
    equipment: ExerciseEquipment.smithMachine,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'sentadilla_goblet',
      'prensa_piernas',
      'extension_cuadriceps',
    ],
    techniqueSteps: [
      'Coloca la barra sobre la parte alta de la espalda y pies en posición estable.',
      'Baja manteniendo rodillas alineadas y tronco firme.',
      'Sube empujando el suelo sin perder la trayectoria guiada.',
    ],
    commonMistakes: [
      'Colocar los pies demasiado lejos sin control.',
      'Dejar que las rodillas colapsen hacia dentro.',
      'Relajar el abdomen en la parte baja.',
    ],
    safetyNote:
        'Ajusta los topes y usa un rango que puedas controlar sin molestias.',
    imageAsset: 'assets/exercises/sentadilla_multipower.png',
  ),
  ExerciseLibraryItem(
    id: 'extension_cuadriceps',
    name: 'Extensión de cuádriceps',
    primaryMuscle: ExerciseMuscles.quadriceps,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.kneeExtension,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'prensa_piernas',
      'sentadilla_goblet',
      'sentadilla_multipower',
    ],
    techniqueSteps: [
      'Ajusta el respaldo y el rodillo cerca del empeine.',
      'Extiende las rodillas con control sin despegar la cadera del asiento.',
      'Baja lento manteniendo tensión en el cuádriceps.',
    ],
    commonMistakes: [
      'Balancear el cuerpo para subir la carga.',
      'Bloquear las rodillas con brusquedad.',
      'Ajustar mal el eje de la máquina.',
    ],
    safetyNote:
        'Si notas molestia en la rodilla, reduce carga, revisa el ajuste o elige otra opción.',
    imageAsset: 'assets/exercises/extension_cuadriceps.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_femoral_sentado',
    name: 'Curl femoral sentado',
    primaryMuscle: ExerciseMuscles.hamstrings,
    secondaryMuscles: [
      ExerciseMuscles.calves,
    ],
    movementPattern: MovementPatterns.kneeFlexion,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'curl_femoral_tumbado',
      'peso_muerto_rumano',
      'hip_thrust',
    ],
    techniqueSteps: [
      'Ajusta el respaldo y bloquea los muslos con el soporte.',
      'Flexiona las rodillas llevando el rodillo hacia abajo.',
      'Vuelve lento sin perder contacto con el asiento.',
    ],
    commonMistakes: [
      'Levantar la cadera al tirar.',
      'Soltar la carga al volver.',
      'Usar un ajuste que no coincide con la rodilla.',
    ],
    safetyNote:
        'Trabaja con recorrido cómodo y revisa el ajuste si notas tensión rara detrás de la rodilla.',
    imageAsset: 'assets/exercises/curl_femoral_sentado.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_femoral_tumbado',
    name: 'Curl femoral tumbado',
    primaryMuscle: ExerciseMuscles.hamstrings,
    secondaryMuscles: [
      ExerciseMuscles.calves,
    ],
    movementPattern: MovementPatterns.kneeFlexion,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'curl_femoral_sentado',
      'peso_muerto_rumano',
      'hip_thrust',
    ],
    techniqueSteps: [
      'Túmbate con rodillas alineadas con el eje de la máquina.',
      'Flexiona las rodillas llevando el rodillo hacia los glúteos.',
      'Baja con control hasta casi extender las piernas.',
    ],
    commonMistakes: [
      'Arquear la espalda al subir.',
      'Separar la cadera del banco.',
      'Hacer repeticiones demasiado rápidas.',
    ],
    safetyNote:
        'Si aparece molestia lumbar, reduce carga y mantén la cadera pegada al banco.',
    imageAsset: 'assets/exercises/curl_femoral_tumbado.png',
  ),
  ExerciseLibraryItem(
    id: 'hip_thrust',
    name: 'Hip thrust',
    primaryMuscle: ExerciseMuscles.glutes,
    secondaryMuscles: [
      ExerciseMuscles.hamstrings,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.hipExtension,
    equipment: ExerciseEquipment.barbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'peso_muerto_rumano',
      'sentadilla_goblet',
      'prensa_piernas',
    ],
    techniqueSteps: [
      'Apoya la parte alta de la espalda en el banco y coloca los pies firmes.',
      'Eleva la cadera hasta alinear torso y muslos sin hiperextender la espalda.',
      'Baja controlando y manteniendo la barra estable sobre la pelvis.',
    ],
    commonMistakes: [
      'Subir arqueando la zona lumbar.',
      'Colocar los pies demasiado lejos o demasiado cerca.',
      'Perder estabilidad del banco.',
    ],
    safetyNote:
        'Usa acolchado y una carga que permita controlar la pelvis durante todo el recorrido.',
    imageAsset: 'assets/exercises/hip_thrust.png',
  ),
  ExerciseLibraryItem(
    id: 'gemelo_sentado',
    name: 'Gemelo sentado',
    primaryMuscle: ExerciseMuscles.calves,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.ankleExtension,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'gemelo_de_pie',
      'prensa_piernas',
      'caminata_cinta',
    ],
    techniqueSteps: [
      'Coloca la parte delantera del pie en la plataforma y ajusta el apoyo de muslos.',
      'Eleva los talones con pausa breve arriba.',
      'Baja controlando hasta un estiramiento cómodo.',
    ],
    commonMistakes: [
      'Rebotar en la parte baja.',
      'Acortar demasiado el recorrido.',
      'Dejar que los pies giren sin control.',
    ],
    safetyNote:
        'Evita rebotes y ajusta la carga si notas tensión incómoda en el tendón de Aquiles.',
    imageAsset: 'assets/exercises/gemelo_sentado.png',
  ),
  ExerciseLibraryItem(
    id: 'gemelo_de_pie',
    name: 'Gemelo de pie',
    primaryMuscle: ExerciseMuscles.calves,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.ankleExtension,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'gemelo_sentado',
      'prensa_piernas',
      'caminata_cinta',
    ],
    techniqueSteps: [
      'Apoya los hombros o manos según la máquina y mantén rodillas estables.',
      'Sube los talones empujando con la parte delantera del pie.',
      'Baja lento sin perder alineación del tobillo.',
    ],
    commonMistakes: [
      'Flexionar y extender rodillas para ayudar.',
      'Rebotar con demasiada velocidad.',
      'Cargar más de lo que permite el rango completo.',
    ],
    safetyNote:
        'Controla la bajada y no fuerces si aparece molestia en tobillo o Aquiles.',
    imageAsset: 'assets/exercises/gemelo_de_pie.png',
  ),
  ExerciseLibraryItem(
    id: 'press_militar_mancuernas',
    name: 'Press militar con mancuernas',
    primaryMuscle: ExerciseMuscles.shoulders,
    secondaryMuscles: [
      ExerciseMuscles.triceps,
      ExerciseMuscles.core,
    ],
    movementPattern: MovementPatterns.verticalPush,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.main,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.strength,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_hombro_maquina',
      'elevaciones_laterales',
      'face_pull',
    ],
    techniqueSteps: [
      'Coloca las mancuernas a la altura de hombros con tronco firme.',
      'Empuja hacia arriba sin arquear la espalda.',
      'Baja controlando hasta una altura cómoda.',
    ],
    commonMistakes: [
      'Compensar con extensión lumbar.',
      'Subir los hombros hacia el cuello.',
      'Descoordinar las mancuernas.',
    ],
    safetyNote:
        'Si no puedes estabilizar ambas mancuernas, baja carga o usa máquina.',
    imageAsset: 'assets/exercises/press_militar_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'elevaciones_laterales',
    name: 'Elevaciones laterales',
    primaryMuscle: ExerciseMuscles.shoulders,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.shoulderAbduction,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'press_hombro_maquina',
      'press_militar_mancuernas',
      'face_pull',
    ],
    techniqueSteps: [
      'Sujeta las mancuernas a los lados con codos ligeramente flexionados.',
      'Eleva los brazos hasta cerca de la altura de los hombros.',
      'Baja lento manteniendo tensión y postura estable.',
    ],
    commonMistakes: [
      'Balancear el cuerpo para iniciar el movimiento.',
      'Subir las manos mucho más que los codos.',
      'Encoger los hombros durante la subida.',
    ],
    safetyNote:
        'Usa cargas ligeras o moderadas y no fuerces si el hombro se irrita.',
    imageAsset: 'assets/exercises/elevaciones_laterales.png',
  ),
  ExerciseLibraryItem(
    id: 'pajaros_mancuernas',
    name: 'Pájaros con mancuernas',
    primaryMuscle: ExerciseMuscles.shoulders,
    secondaryMuscles: [
      ExerciseMuscles.back,
    ],
    movementPattern: MovementPatterns.shoulderHorizontalAbduction,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'face_pull',
      'remo_maquina',
      'elevaciones_laterales',
    ],
    techniqueSteps: [
      'Inclina el torso con espalda estable y mancuernas bajo los hombros.',
      'Abre los brazos en arco corto llevando los codos hacia fuera.',
      'Baja controlando sin perder la posición del tronco.',
    ],
    commonMistakes: [
      'Usar impulso de espalda.',
      'Llevar las mancuernas demasiado atrás.',
      'Encoger el cuello al subir.',
    ],
    safetyNote:
        'Prioriza control y rango cómodo antes que carga alta.',
    imageAsset: 'assets/exercises/pajaros_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'face_pull',
    name: 'Face pull',
    primaryMuscle: ExerciseMuscles.shoulders,
    secondaryMuscles: [
      ExerciseMuscles.back,
    ],
    movementPattern: MovementPatterns.shoulderHorizontalAbduction,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'pajaros_mancuernas',
      'remo_maquina',
      'elevaciones_laterales',
    ],
    techniqueSteps: [
      'Coloca la cuerda a la altura de la cara y da un paso atrás.',
      'Tira hacia la cara separando las manos y manteniendo codos altos.',
      'Vuelve lento sin perder la posición de cuello y hombros.',
    ],
    commonMistakes: [
      'Tirar hacia el pecho en lugar de hacia la cara.',
      'Arquear la espalda.',
      'Usar demasiado peso y perder recorrido.',
    ],
    safetyNote:
        'Elige una carga que permita mover hombros y escápulas sin tirones.',
    imageAsset: 'assets/exercises/face_pull.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_biceps_barra_z',
    name: 'Curl bíceps barra Z',
    primaryMuscle: ExerciseMuscles.biceps,
    secondaryMuscles: [
      ExerciseMuscles.forearms,
    ],
    movementPattern: MovementPatterns.elbowFlexion,
    equipment: ExerciseEquipment.ezBar,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'curl_biceps_mancuernas',
      'curl_predicador_maquina',
      'curl_martillo',
    ],
    techniqueSteps: [
      'Sujeta la barra Z con agarre cómodo y codos cerca del cuerpo.',
      'Flexiona los codos sin balancear el tronco.',
      'Baja controlando hasta casi extender los brazos.',
    ],
    commonMistakes: [
      'Impulsar la barra con la cadera.',
      'Mover los codos hacia delante en exceso.',
      'Acortar la bajada.',
    ],
    safetyNote:
        'Mantén muñecas cómodas y reduce carga si notas tensión en codos.',
    imageAsset: 'assets/exercises/curl_biceps_barra_z.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_predicador_maquina',
    name: 'Curl predicador máquina',
    primaryMuscle: ExerciseMuscles.biceps,
    secondaryMuscles: [
      ExerciseMuscles.forearms,
    ],
    movementPattern: MovementPatterns.elbowFlexion,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'curl_biceps_barra_z',
      'curl_biceps_mancuernas',
      'curl_martillo',
    ],
    techniqueSteps: [
      'Ajusta el asiento para apoyar brazos y pecho de forma cómoda.',
      'Flexiona los codos manteniendo los brazos sobre el soporte.',
      'Baja lento sin perder tensión al final.',
    ],
    commonMistakes: [
      'Separar los brazos del apoyo.',
      'Extender de golpe en la parte baja.',
      'Usar un rango doloroso para el codo.',
    ],
    safetyNote:
        'No fuerces la extensión si el codo se siente incómodo; ajusta rango o carga.',
    imageAsset: 'assets/exercises/curl_predicador_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'curl_martillo',
    name: 'Curl martillo',
    primaryMuscle: ExerciseMuscles.biceps,
    secondaryMuscles: [
      ExerciseMuscles.forearms,
    ],
    movementPattern: MovementPatterns.elbowFlexion,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'curl_biceps_mancuernas',
      'curl_biceps_barra_z',
      'curl_predicador_maquina',
    ],
    techniqueSteps: [
      'Sujeta las mancuernas con palmas enfrentadas.',
      'Flexiona los codos sin girar la muñeca.',
      'Baja con control manteniendo los codos cerca del torso.',
    ],
    commonMistakes: [
      'Balancear el cuerpo.',
      'Subir los hombros al flexionar.',
      'Perder posición neutra de muñeca.',
    ],
    safetyNote:
        'Usa una carga que no obligue a compensar con espalda o hombros.',
    imageAsset: 'assets/exercises/curl_martillo.png',
  ),
  ExerciseLibraryItem(
    id: 'triceps_polea_barra',
    name: 'Tríceps polea con barra',
    primaryMuscle: ExerciseMuscles.triceps,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.elbowExtension,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'triceps_polea_cuerda',
      'press_frances_mancuernas',
      'fondos_banco',
    ],
    techniqueSteps: [
      'Colócate cerca de la polea con codos fijos junto al cuerpo.',
      'Extiende los codos llevando la barra hacia abajo.',
      'Sube controlando hasta que el antebrazo vuelva sin mover el hombro.',
    ],
    commonMistakes: [
      'Inclinarse demasiado para empujar.',
      'Abrir los codos hacia los lados.',
      'Usar recorrido parcial sin control.',
    ],
    safetyNote:
        'Ajusta carga y agarre si notas molestias en codos o muñecas.',
    imageAsset: 'assets/exercises/triceps_polea_barra.png',
  ),
  ExerciseLibraryItem(
    id: 'press_frances_mancuernas',
    name: 'Press francés con mancuernas',
    primaryMuscle: ExerciseMuscles.triceps,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.elbowExtension,
    equipment: ExerciseEquipment.dumbbell,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'triceps_polea_cuerda',
      'triceps_polea_barra',
      'fondos_banco',
    ],
    techniqueSteps: [
      'Túmbate o siéntate con las mancuernas estables sobre los hombros.',
      'Flexiona los codos llevando la carga hacia atrás con control.',
      'Extiende los codos sin mover demasiado los brazos.',
    ],
    commonMistakes: [
      'Abrir los codos en exceso.',
      'Perder control en la bajada.',
      'Elegir una carga que obliga a arquear la espalda.',
    ],
    safetyNote:
        'Mantén un rango cómodo para codo y hombro; cambia a polea si necesitas más estabilidad.',
    imageAsset: 'assets/exercises/press_frances_mancuernas.png',
  ),
  ExerciseLibraryItem(
    id: 'fondos_banco',
    name: 'Fondos en banco',
    primaryMuscle: ExerciseMuscles.triceps,
    secondaryMuscles: [
      ExerciseMuscles.chest,
      ExerciseMuscles.shoulders,
    ],
    movementPattern: MovementPatterns.elbowExtension,
    equipment: ExerciseEquipment.bodyweight,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'triceps_polea_cuerda',
      'triceps_polea_barra',
      'fondos_asistidos',
    ],
    techniqueSteps: [
      'Apoya las manos en el banco con hombros bajos y pies firmes.',
      'Baja flexionando codos hasta un rango cómodo.',
      'Empuja el banco para subir sin bloquear con brusquedad.',
    ],
    commonMistakes: [
      'Bajar demasiado y forzar el hombro.',
      'Alejar demasiado la cadera del banco.',
      'Hacer el movimiento rápido y sin control.',
    ],
    safetyNote:
        'Si el hombro se siente incómodo, reduce recorrido o cambia a polea.',
    imageAsset: 'assets/exercises/fondos_banco.png',
  ),
  ExerciseLibraryItem(
    id: 'plancha',
    name: 'Plancha',
    primaryMuscle: ExerciseMuscles.core,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
      ExerciseMuscles.glutes,
    ],
    movementPattern: MovementPatterns.antiExtension,
    equipment: ExerciseEquipment.bodyweight,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'pallof_press',
      'crunch_maquina',
      'elevacion_rodillas',
    ],
    techniqueSteps: [
      'Apoya antebrazos y pies con el cuerpo alineado.',
      'Activa abdomen y glúteos sin hundir la cadera.',
      'Mantén respiración controlada durante el tiempo indicado.',
    ],
    commonMistakes: [
      'Elevar demasiado la cadera.',
      'Hundirse en la zona lumbar.',
      'Aguantar la respiración.',
    ],
    safetyNote:
        'Termina la serie si pierdes alineación o aparece molestia lumbar.',
    imageAsset: 'assets/exercises/plancha.png',
  ),
  ExerciseLibraryItem(
    id: 'crunch_maquina',
    name: 'Crunch en máquina',
    primaryMuscle: ExerciseMuscles.core,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.trunkFlexion,
    equipment: ExerciseEquipment.machine,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'crunch_polea',
      'plancha',
      'elevacion_rodillas',
    ],
    techniqueSteps: [
      'Ajusta la máquina para que el movimiento salga desde el abdomen.',
      'Flexiona el tronco de forma controlada sin tirar del cuello.',
      'Vuelve lento manteniendo tensión.',
    ],
    commonMistakes: [
      'Tirar con brazos o cuello.',
      'Usar demasiada carga.',
      'Hacer rebotes al final.',
    ],
    safetyNote:
        'Usa una carga moderada y evita rangos que molesten la espalda.',
    imageAsset: 'assets/exercises/crunch_maquina.png',
  ),
  ExerciseLibraryItem(
    id: 'crunch_polea',
    name: 'Crunch en polea',
    primaryMuscle: ExerciseMuscles.core,
    secondaryMuscles: [],
    movementPattern: MovementPatterns.trunkFlexion,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'crunch_maquina',
      'plancha',
      'pallof_press',
    ],
    techniqueSteps: [
      'Colócate de rodillas frente a la polea alta con cuerda estable.',
      'Flexiona el tronco llevando costillas hacia pelvis.',
      'Regresa con control sin perder tensión abdominal.',
    ],
    commonMistakes: [
      'Tirar con los brazos.',
      'Sentarse sobre los talones en cada repetición.',
      'Convertirlo en un balanceo de cadera.',
    ],
    safetyNote:
        'Ajusta la carga si notas que compensas con espalda o cuello.',
    imageAsset: 'assets/exercises/crunch_polea.png',
  ),
  ExerciseLibraryItem(
    id: 'pallof_press',
    name: 'Pallof press',
    primaryMuscle: ExerciseMuscles.core,
    secondaryMuscles: [
      ExerciseMuscles.shoulders,
      ExerciseMuscles.glutes,
    ],
    movementPattern: MovementPatterns.antiRotation,
    equipment: ExerciseEquipment.cable,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'plancha',
      'crunch_polea',
      'elevacion_rodillas',
    ],
    techniqueSteps: [
      'Colócate de lado a la polea con agarre a la altura del pecho.',
      'Empuja las manos al frente sin dejar que el tronco rote.',
      'Vuelve al pecho manteniendo pelvis y hombros cuadrados.',
    ],
    commonMistakes: [
      'Girar el tronco hacia la polea.',
      'Encoger hombros.',
      'Usar una carga que impide quedarse estable.',
    ],
    safetyNote:
        'Reduce carga si no puedes mantener postura neutra y respiración fluida.',
    imageAsset: 'assets/exercises/pallof_press.png',
  ),
  ExerciseLibraryItem(
    id: 'elevacion_rodillas',
    name: 'Elevación de rodillas',
    primaryMuscle: ExerciseMuscles.core,
    secondaryMuscles: [
      ExerciseMuscles.quadriceps,
    ],
    movementPattern: MovementPatterns.hipFlexion,
    equipment: ExerciseEquipment.bodyweight,
    level: ExerciseLevels.intermediate,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.hypertrophy,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'plancha',
      'crunch_maquina',
      'crunch_polea',
    ],
    techniqueSteps: [
      'Apóyate en paralelas o estación romana con hombros estables.',
      'Eleva rodillas hacia el pecho controlando la pelvis.',
      'Baja lento sin balancear el cuerpo.',
    ],
    commonMistakes: [
      'Balancearse para subir las rodillas.',
      'Perder apoyo de hombros.',
      'Bajar las piernas sin control.',
    ],
    safetyNote:
        'Si no puedes evitar el balanceo, reduce rango o usa una variante más sencilla.',
    imageAsset: 'assets/exercises/elevacion_rodillas.png',
  ),
  ExerciseLibraryItem(
    id: 'caminata_cinta',
    name: 'Caminata en cinta',
    primaryMuscle: ExerciseMuscles.cardiovascular,
    secondaryMuscles: [
      ExerciseMuscles.quadriceps,
      ExerciseMuscles.glutes,
      ExerciseMuscles.calves,
    ],
    movementPattern: MovementPatterns.cyclicCardio,
    equipment: ExerciseEquipment.treadmill,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'bicicleta_estatica',
      'eliptica',
      'gemelo_de_pie',
    ],
    techniqueSteps: [
      'Elige una velocidad que permita caminar con postura natural.',
      'Mantén mirada al frente y pisada cómoda.',
      'Ajusta inclinación y duración de forma progresiva.',
    ],
    commonMistakes: [
      'Agarrarse fuerte a los pasamanos todo el tiempo.',
      'Subir demasiado la inclinación de golpe.',
      'Alargar la zancada de forma artificial.',
    ],
    safetyNote:
        'Empieza suave y reduce velocidad si pierdes coordinación o estabilidad.',
    imageAsset: 'assets/exercises/caminata_cinta.png',
  ),
  ExerciseLibraryItem(
    id: 'bicicleta_estatica',
    name: 'Bicicleta estática',
    primaryMuscle: ExerciseMuscles.cardiovascular,
    secondaryMuscles: [
      ExerciseMuscles.quadriceps,
      ExerciseMuscles.hamstrings,
      ExerciseMuscles.glutes,
    ],
    movementPattern: MovementPatterns.cyclicCardio,
    equipment: ExerciseEquipment.stationaryBike,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'caminata_cinta',
      'eliptica',
      'prensa_piernas',
    ],
    techniqueSteps: [
      'Ajusta el sillín para pedalear con rodilla ligeramente flexionada abajo.',
      'Mantén cadencia cómoda y tronco relajado.',
      'Regula resistencia según el objetivo de la sesión.',
    ],
    commonMistakes: [
      'Llevar el sillín demasiado bajo.',
      'Pedalear con tensión excesiva en hombros.',
      'Subir resistencia antes de calentar.',
    ],
    safetyNote:
        'Revisa el ajuste si notas molestias en rodilla, cadera o zona lumbar.',
    imageAsset: 'assets/exercises/bicicleta_estatica.png',
  ),
  ExerciseLibraryItem(
    id: 'eliptica',
    name: 'Elíptica',
    primaryMuscle: ExerciseMuscles.cardiovascular,
    secondaryMuscles: [
      ExerciseMuscles.quadriceps,
      ExerciseMuscles.glutes,
      ExerciseMuscles.calves,
    ],
    movementPattern: MovementPatterns.cyclicCardio,
    equipment: ExerciseEquipment.elliptical,
    level: ExerciseLevels.beginner,
    recommendedRole: ExerciseRoles.accessory,
    compatibleGoals: [
      ExerciseGoals.adaptation,
      ExerciseGoals.recomposition,
    ],
    alternatives: [
      'caminata_cinta',
      'bicicleta_estatica',
      'gemelo_sentado',
    ],
    techniqueSteps: [
      'Sube con cuidado y encuentra un ritmo fluido.',
      'Mantén postura alta y presión estable sobre los pedales.',
      'Usa brazos móviles si puedes coordinarlos sin tensión.',
    ],
    commonMistakes: [
      'Apoyarse demasiado sobre las manos.',
      'Hacer zancadas cortas y bruscas.',
      'Cambiar resistencia sin controlar el ritmo.',
    ],
    safetyNote:
        'Empieza con resistencia baja y baja el ritmo si pierdes equilibrio o coordinación.',
    imageAsset: 'assets/exercises/eliptica.png',
  ),
];
